ALTER TABLE api_keys
    ADD COLUMN IF NOT EXISTS allowed_models TEXT[] DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS max_spend_usd DOUBLE PRECISION DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS requests_per_minute INTEGER DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS requests_per_day INTEGER DEFAULT NULL;
